# Arquivo com as dependências (gems) do projeto
# Instalar -> bundle install

# Instalando as gems através do Gemfile para que não precisemos instalar uma por vez

source 'https://rubygems.org/'

gem 'cpf_utils'